version: "3.0"

services:      
  studiobookingdb:
    image: postgres:15
    container_name: studio-booking-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studiobooking
    ports:
      - "5436:5432"
    volumes:
      - studio_booking_vol:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - net-bms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d studiobooking"]
      interval: 10s
      timeout: 5s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: always
    ports:
      - "5402:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin.search@zageno.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - net-bms
    volumes:
      - pgadmin-data_vol:/var/lib/pgadmin

volumes:
  bms_vol:
  pgadmin-data_vol:
  studio_booking_vol:


networks:
  net-bms:












